#! /bin/bash

GENERATORPATH=$HOME/TraceGenerator
JALANGIPATH=$HOME/jalangi2
NODEPATH=/home/jkloos/node

set +o pipefail

$NODEPATH/bin/node \
  --harmony $JALANGIPATH/src/js/commands/jalangi.js \
  --inlineIID --inlineSource \
  --analysis $GENERATORPATH/collect_trace.js \
  $1 |tail -1 >${1%.js}.trace

